name: attendance_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.0

  firebase_core: ^2.25.4

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository
  course_repository:
    path: packages/course_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
